CREATE TABLE [dbo].[Tier]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Rank] INT NOT NULL, 
    [Description] NVARCHAR(MAX) NOT NULL,

    [CreatedDate] DATETIME2 NOT NULL DEFAULT GETUTCDATE(), 
[LastModified]DATETIME2 NOT NULL DEFAULT GETUTCDATE()
)
